### ISSUE TITLE
Error while running the application

### ISSUE THREAD

**Issue by diegobernardes** [owulveryck/gofaces#3]
This is the error that I got running the aplication following the instructions on the readme:
```
➜ go run main.go
2019/08/20 10:22:48 proto: can't skip unknown wire type 6
exit status 1
```

The problem was related to the model file. it was not downloaded because it's being handled by `git lfs`. Would be nice to mention this on the readme and show how the file could be fetched.

Another good thing is to lock the dependencies, maybe with the `go modules`? if you want, I can send a PR.

**Comment by owulveryck** [comment]
Hello,

Thank you for reporting this.
Thank you for your proposal, a PR is welcome 👍
